---
spring:
  cloud:
    bus: true
    config:
      server:
        git:
          uri: https://github.com/jayallenmn/blog-spring-cloud-config-configuration.git
        #native:
        #  searchLocations: classpath:/config

server:
  port: 8888
